### ISSUE TITLE
Drag & Drop for images in VS Code

### ISSUE THREAD

**Issue by makaroni4** [makaroni4/notenote#2]
# TODO

- [x] Catch drag & drop event in the window
- [x] Learn how to get filename from the event
- [x] Configure `images` folder
- [x] How to organize images in a folder? `images/DATE/file.png` ?
- [x] Learn how to copy dropped file to the images folder
- [x] Learn how to insert an image to Markdown in the position of the cursor
- [x] How to disable Markdown Drop only for daily notes folder?
- [x] Figure out snippets for images and other files
- [x] Disable extension outside of notes folder
- [x] What if a file exists? How to show an error in VS Code?

**Comment by makaroni4** [comment]
https://code.visualstudio.com/docs/languages/markdown#_drag-and-drop-to-insert-links-and-images

**Comment by makaroni4** [comment]
https://github.com/microsoft/vscode-extension-samples/issues/741
